config/routes.rb
WhatTodo::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :lists
  resources :tasks
  
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  	
  	def home
  		store_path root_path
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_important_list.html.erb
<div class="task_container">
	<div class="task_name_container">
		<% if current_user.lists.any? %>
			<% current_user.lists.each do |list| %>
				<% legit = false %>
				<% list.tasks.each do |task| %>
					<% if task.important && !task.status %>
						<% legit = true %>
					<% end %>
				<% end %>
				<% if legit == true %>
					<% if list.tasks.any? %>
						<div class="tasks">
							<ul>
								<% num_tasks_left = list.tasks.find_all_by_status(false) %>
								<h3 id="important-list-name"><%= link_to "#{list.category} (#{num_tasks_left.count})", list_path(list) %></h3>
								<% list.tasks.each do |task| %>
									<% if task.important && !task.status %>
										<%= render 'static_pages/important_task_options', task: task %>
										<li>
										 	<span class="content">
										 		<%= task.content %>	
										 	</span>
										  	<span class="timestamp">
										   		Posted <%= time_ago_in_words(task.created_at) %> ago.
										  	</span>
										</li>
									<% end %>
								<% end %>
							</ul>
						</div>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	</div><!-- end of task_name_container -->
</div>

app/views/static_pages/_important_task_options.html.erb
<div id="task_options">
	<div class="dropdown">
	    <button type="button" class="btn btn-default dropdown-toggle" 
	   	    	data-toggle="dropdown">Options <span class="caret"></span></button>
	    <ul class="dropdown-menu">
	      	<% if !task.important %>
	    		<li><%= link_to 'important', task_path(id: task.id, 
	    		content: task.content, status: task.status, 
	    		important: true), method: :patch %></li> 
		   	<% else %>
				<li><%= link_to 'unimportant', task_path(id: task.id, 
				content: task.content, status: task.status, 
				important: false), method: :patch %></li> 
		 	<% end %>
		    <li><%= link_to 'edit', edit_task_path(task) %></li>
	        <!--<li class="divider"></li>-->
	        <li><%= link_to 'delete', task, id:"delete-task-btn",
		        		method: :delete, data: { confirm: "Are you sure?"} %></li>
	    </ul>
	</div>
</div>

<% if !task.status %>
	<div class="complete-btn">
		<%= button_to "complete", task_path(id: task.id, content: task.content, status: true, important: task.important), method: :patch %>
	</div>
<% else %>
	<div class="complete-btn">
		<%= button_to "incomplete", task_path(id: task.id, content: task.content, status: false, important: task.important), method: :patch %>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<h1>Important Tasks</h1>
<%= render 'static_pages/important_list' %>
<% else %>
	<div class="center hero-unit">
		<h1>Welcome to What-ToDo</h1>

		<h2>Your personal To-Do list</h2>

		<%= link_to "Sign up now!", signup_path, class:"btn btn-large btn-primary" %>
	</div>
<% end %>